import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import StoreProvider from "@/store/StoreProvider";
import Header from "@/components/Header";
import BottomNav from "@/components/BottomNav";
import GlobalLoader from "@/components/GlobalLoader";
import TesterWelcomePopup from "@/components/TesterWelcomePopup";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* <body className="min-h-full flex flex-col">
        <StoreProvider>
          <Header />
          
          <main className="flex-1">{children}</main>
          <Footer />
          <BottomNav />
          <Toaster />
        </StoreProvider>
        <Script src="https://accounts.google.com/gsi/client" strategy="beforeInteractive" />
      </body> */}

      <body className="min-h-screen flex flex-col">
  <StoreProvider>

    {/* Global Route Loader */}
    <GlobalLoader />

    {/* Tester Welcome Popup (Only shows first time) */}
    <TesterWelcomePopup />

    {/* Header */}
    <Header />

    {/* Main Content */}
    <main className="flex-1 pt-[80px]">
      {children}
    </main>

    {/* Mobile Bottom Nav */}
    <BottomNav />

    {/* Toast */}
    <Toaster />

  </StoreProvider>

  <Script
    src="https://accounts.google.com/gsi/client"
    strategy="beforeInteractive"
  />
</body>
    </html>
  );
}
